# Generated by Django 5.1.6 on 2025-03-13 02:25

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('msg', models.TextField(max_length=1000)),
                ('unlock_at', models.DateField()),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('email', models.EmailField(max_length=254)),
                ('is_public', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
