# Generated by Django 5.1.6 on 2025-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capsule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('upload', models.FileField(upload_to='uploads/')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
