# Generated by Django 5.1.6 on 2025-03-15 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='msg',
            field=models.TextField(max_length=10000),
        ),
        migrations.CreateModel(
            name='CapsuleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='capsule.capsule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapsuleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='capsule.capsule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
