# Generated by Django 5.1.6 on 2025-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='capsule',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
