# Generated by Django 5.1.6 on 2025-03-11 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0002_capsule_is_public_alter_capsule_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capsule',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CapsuleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='capsule.capsule')),
            ],
            options={
                'unique_together': {('capsule', 'email')},
            },
        ),
    ]
