# Generated by Django 5.1.6 on 2025-03-15 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0002_alter_capsule_msg_capsulecomment_capsulelike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsulelike',
            name='capsule',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsule.capsule')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capsule.capsule')),
            ],
        ),
        migrations.DeleteModel(
            name='CapsuleComment',
        ),
        migrations.DeleteModel(
            name='CapsuleLike',
        ),
    ]
