# Generated by Django 5.1.6 on 2025-03-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0003_capsule_rating_capsule_rating_count_capsulerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='capsule',
            name='rating_count',
        ),
        migrations.DeleteModel(
            name='CapsuleRating',
        ),
    ]
