# Generated by Django 5.1.6 on 2025-03-12 02:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0004_remove_capsule_rating_remove_capsule_rating_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
