# Generated by Django 5.1.6 on 2025-03-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0004_remove_like_capsule_delete_comment_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsule',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='capsule',
            name='password',
        ),
    ]
