# Generated by Django 5.1.6 on 2025-04-09 22:21

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0005_remove_capsule_is_public_remove_capsule_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='upload',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
    ]
