# Generated by Django 5.1.6 on 2025-03-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0005_capsule_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsule',
            old_name='date',
            new_name='unlock_at',
        ),
    ]
