# Generated by Django 5.1.6 on 2025-04-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0007_capsule_upload_status_alter_capsule_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capsule',
            name='upload',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
