# Generated by Django 5.1.6 on 2025-04-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsule', '0008_alter_capsule_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsule',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
